py_binary(
    name = "sample",
    srcs = ["python/sample.py"],
    deps = ["myClass"],
)

py_library(
    name = "myClass",
    srcs = ["python/klasa.py"],
    visibility = ["//visibility:public"],
)
